server:
  port: 8080

spring:
  application:
    name: newsletter
  datasource:
    url: jdbc:postgresql://localhost:5432/designlog
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


